sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t 13579246789/reactapp_singlecont -f Dockerfile.dev .

script:
  - docker run -e CI=true 13579246789/reactapp_singlecont npm run test -- --coverage
