version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - /home/node/reactapp/node_modules
      - .:/home/node/reactapp
  tests:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /home/node/reactapp/node_modules
      - .:/app
    command: ["npm", "run", "test"]
