FROM node:18-alpine
 
USER node
 
RUN mkdir -p /home/node/reactapp
WORKDIR /home/node/reactapp
 
COPY --chown=node:node ./package.json ./
RUN npm install
COPY --chown=node:node ./ ./

CMD ["npm", "start"]